OCI_MODEL_ID = "cohere.command-r-plus-08-2024"
OCI_ENDPOINT = "https://inference.generativeai.us-chicago-1.oci.oraclecloud.com"
OCI_COMPARTMENT_OCID = "ocid1.compartment.oc1..aaaaaaaaxj6dyzjb6zggtwoaavl6apkzzgd7tv3lykpl6bmmf6iffegu5woa"

OCI_TENANCY_OCID = "ocid1.tenancy.oc1..aaaaaaaaiqbmytkqxr557ogg367pmnuurzjy27pmfrifzb35uymskjik2bwa"
OCI_USER_OCID = "ocid1.user.oc1..aaaaaaaalfqefkjgptsg6vzzue4o7uddjquj6skwue3h52nuvhfwriq5yizq"
OCI_FINGERPRINT = "fe:58:21:18:4c:aa:38:0f:3e:65:1d:f5:c2:1e:13:98"

OCI_PRIVATE_KEY = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQClS7tJQ8TZBhUo
PJmmPVjyJVY517naiBA/IjLMQnYI8XEnYRE0AoFKFNRRuAyDRUHUCsYtDzsWXix7
iDhi/wsiiBfjURMMlLFg6HcruF0UmwOGiBUO2sQTZb+mvcWShc+KoR7kCb2rN2yB
djz7t3DEzk63qZY4AewXSlodBgUxS322znMVVkPKCTHUk82I9eAdoxsPFDEhNW0W
YF9BV3bFq9yJlANq9WpjrS2m2/aQbn62i/TvvHDGWVfwHHaZXp1mwiiMzRIYldY5
ykjWyJi07OE8aldwDjNib47xPZ64cJyq989aOgO1wu4OQKhsCwK1iK1IxkHxcsw3
In2hxk1nAgMBAAECggEAHECM8tFP+G4XOKje9DCBHuYtzjYmkIj4Ceps90eWyCGI
XxwypgqVkZVs0sjb7qXsQfNTewki5shS3wxh4t3Hx++t8Y7+bASQKsmg8MqSsj5q
hFiHDOJsaApYjwXZmpkfZ4jxcDWQAw82jwwoETgB4MmIX9DvGYSOl06Ah3xrb8i6
BhioX3luTGPloLyolKRF6U6V5zmv4iCoqmhddtjEXcrUGUqE7LwF6GOR7XIHLHXU
Bon4qvoxCxxt1okmO8GX+CwWntEhlOcONbSvvJZg1BbzRs8Q2tPRepLRm3CvtFGe
d1Ft7C/pkS+ZIp7KrRialzyx5+jA2PuE4AOpuDG0UQKBgQDpEeQZtcPzHsqNwOqH
JwMOJf5pRIxwxH3/aK8LRBip11yRpA5pJ9iiTiMx29cy5D2vUIhv+w1IUEExFPST
RS8dTy0G/dm3OFKQuzBysnH3G8h8eB3Uqu64opzoFY2Ch0LAuOIF67M08zqJ4rVk
uDp65klVhlaIuv2ipjPgxnr/NwKBgQC1juFD6/f5quLQFEtq2dJPHU6TVLoS2Mdo
fTUBOtICnSCpSulMcC6PDcTk54HaezPxBRbzuCKyRqNy1dTC9UyiWCTdem7t6DCk
j8FaPmOxu+KrGCSGG/ERORpIpdBsKI5GJmaGWjOf2YI/ZJP5/Tcp9oEUTaX+/gXG
WxZFSHVbUQKBgQDocpF+GsxNIz581hSRqpTffYEY1+cBaNcI7gz2PXojmciW8Hn2
4miqpyduyIT+Gqhyuuz4UfhTUMdT/kRWxL9Sie6sdGy40RF3i1msatBC1ZDEor+N
pNTljDjVNvmlXuVydHHn2cUnYBXYAyVKSHr6q8Yj6BFR2LyxhPVkjk+JTQKBgF4R
nZ23kVAGvmXZXgoKufDL2n5zk8VYFFmLJf9xHobEKrwMWDyGk1kDZVTErn8o/oyO
eonkifWcq+s/53Dr77zdtpwaZ4dUmn9pDGFZmgXot1S2uZXSvGCUGY4ye37OtIic
NNq/uafE5rs5vYH1NLPFSLPgV3V64DsZzrwvAr9BAoGAbZK8hms26vuIkGTwrdiB
NPV0zTyCzm2+1B3UIaY3Ewae1n5V5vnIoA24eiZeFGbWX93nLVwqSgZcH57kngb5
1/p0eg1VQxo1Kz8Nfjb422npJBe8j5nZrH5FKGnmBHmBib+jxuJzx1yoPYpNWxod
RDNc3mhEx9+FvdHVGodhrM0=
-----END PRIVATE KEY-----
"""

OCI_API_KEY = "your_api_key_here"

LLM_TEMPERATURE = 0.0
LLM_MAX_TOKENS = 800

